<?php

namespace AppBundle\Repository;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends \Doctrine\ORM\EntityRepository
{
    public function getEvent(string $id)
    {
        $event = $this->find($id);

        if (null === $event) {
            throw new NotFoundHttpException(
            'No event found for id '.$id
        );
        }

        return $event;
    }
}
